// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505045615_AddColumnAddedbyAndEditBy")]
    partial class AddColumnAddedbyAndEditBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AllClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ClaimValue")
                        .HasColumnType("bit");

                    b.Property<string>("groupClaims")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AllClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Authentication Management",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Add User",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Edit User",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "User Activation",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Add Role",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Edit Role",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Role Management",
                            ClaimValue = true,
                            groupClaims = "Authentication"
                        });
                });

            modelBuilder.Entity("Domain.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EditBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = "1",
                            AddedBy = "8498d607-189d-456b-a5ef-7833734fac92",
                            DepartmentName = "ریاست مخابره",
                            EditBy = "8498d607-189d-456b-a5ef-7833734fac92"
                        });
                });

            modelBuilder.Entity("Domain.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankTypeId");

                    b.ToTable("ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "سترپاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "لوی پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "مل پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "سمونوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "سمونمل",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "سمونیار",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "څارمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "لمړی څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "دوهم څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "لمړی ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "دوهم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "دریم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "لمړی ساتونکی",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "دوهم ساتونکی",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "مجاهد",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "خارج رتبه",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "مافوق رتبه",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "فوق رتبه",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "اول",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "دوم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "سوم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "چهارم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "پنجم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "ششم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "هفتم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "هشتم",
                            RankTypeId = 2
                        },
                        new
                        {
                            Id = 28,
                            Name = "A",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "A1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "A2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "A3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "A4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "A5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "A6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 35,
                            Name = "A7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 36,
                            Name = "A8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 37,
                            Name = "A9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            Name = "A10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 39,
                            Name = "B",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 40,
                            Name = "B1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 41,
                            Name = "B2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 42,
                            Name = "B3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 43,
                            Name = "B4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 44,
                            Name = "B5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 45,
                            Name = "B6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 46,
                            Name = "B7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 47,
                            Name = "B8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 48,
                            Name = "B9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 49,
                            Name = "B10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 50,
                            Name = "C",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 51,
                            Name = "C1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 52,
                            Name = "C2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 53,
                            Name = "C3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 54,
                            Name = "C4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 55,
                            Name = "C5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 56,
                            Name = "C6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 57,
                            Name = "C7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 58,
                            Name = "C8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 59,
                            Name = "C9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 60,
                            Name = "C10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 61,
                            Name = "D",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 62,
                            Name = "D1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 63,
                            Name = "D2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 64,
                            Name = "D3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 65,
                            Name = "D4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 66,
                            Name = "D5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 67,
                            Name = "D6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 68,
                            Name = "D7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 69,
                            Name = "D8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 70,
                            Name = "D9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 71,
                            Name = "D10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 72,
                            Name = "E",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 73,
                            Name = "E1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 74,
                            Name = "E2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 75,
                            Name = "E3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 76,
                            Name = "E4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 77,
                            Name = "E5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 78,
                            Name = "E6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 79,
                            Name = "E7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 80,
                            Name = "E8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 81,
                            Name = "E9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 82,
                            Name = "E10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 83,
                            Name = "F",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 84,
                            Name = "F1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 85,
                            Name = "F2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 86,
                            Name = "F3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 87,
                            Name = "F4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 88,
                            Name = "F5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 89,
                            Name = "F6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 90,
                            Name = "F7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 91,
                            Name = "F8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 92,
                            Name = "F9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 93,
                            Name = "F10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 94,
                            Name = "G",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 95,
                            Name = "G1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 96,
                            Name = "G2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 97,
                            Name = "G3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 98,
                            Name = "G4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 99,
                            Name = "G5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 100,
                            Name = "G6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 101,
                            Name = "G7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 102,
                            Name = "G8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 103,
                            Name = "G9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 104,
                            Name = "G10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 105,
                            Name = "H",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 106,
                            Name = "H1",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 107,
                            Name = "H2",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 108,
                            Name = "H3",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 109,
                            Name = "H4",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 110,
                            Name = "H5",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 111,
                            Name = "H6",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 112,
                            Name = "H7",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 113,
                            Name = "H8",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 114,
                            Name = "H9",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 115,
                            Name = "H10",
                            RankTypeId = 3
                        },
                        new
                        {
                            Id = 116,
                            Name = "ندارد",
                            RankTypeId = 4
                        },
                        new
                        {
                            Id = 117,
                            Name = "مجاهد سترپاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 118,
                            Name = "مجاهد لوی پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 119,
                            Name = "مجاهد پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 120,
                            Name = "مجاهد مل پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 121,
                            Name = "مجاهد سمونوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 122,
                            Name = "مجاهد سمونمل",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 123,
                            Name = "مجاهد سمونیار",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 124,
                            Name = "مجاهد څارمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 125,
                            Name = "مجاهد لمړی څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 126,
                            Name = "مجاهد دوهم څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 127,
                            Name = "مجاهد لمړی ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 128,
                            Name = "مجاهد دوهم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 129,
                            Name = "مجاهد دریم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 130,
                            Name = "مجاهد لمړی ساتونکی",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 131,
                            Name = "مجاهد دوهم ساتونکی",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 132,
                            Name = "ملکی در بست سترپاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 133,
                            Name = "ملکی در بست لوی پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 134,
                            Name = "ملکی در بست پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 135,
                            Name = "ملکی در بست مل پاسوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 136,
                            Name = "ملکی در بست سمونوال",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 137,
                            Name = "ملکی در بست سمونمل",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 138,
                            Name = "ملکی در بست سمونیار",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 139,
                            Name = "ملکی در بست څارمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 140,
                            Name = "ملکی در بست لمړی څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 141,
                            Name = "ملکی در بست دوهم څارن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 142,
                            Name = "ملکی در بست لمړی ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 143,
                            Name = "ملکی در بست دوهم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 144,
                            Name = "ملکی در بست دریم ساتنمن",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 145,
                            Name = "ملکی در بست لمړی ساتونکی",
                            RankTypeId = 1
                        },
                        new
                        {
                            Id = 146,
                            Name = "ملکی در بست دوهم ساتونکی",
                            RankTypeId = 1
                        });
                });

            modelBuilder.Entity("Domain.RankType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("rankTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "نظامی"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ملکی"
                        },
                        new
                        {
                            Id = 3,
                            Name = "قراردادی"
                        },
                        new
                        {
                            Id = 4,
                            Name = "بالمقطع"
                        });
                });

            modelBuilder.Entity("Domain.Sells", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sells");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRoleClaim<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "ac976318-0f8a-4a98-81e1-c855bc496cbd",
                            Name = "Super Admin",
                            NormalizedName = "SUPER ADMIN"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.RoleClaims", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>");

                    b.HasDiscriminator().HasValue("RoleClaims");
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Department_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rankid")
                        .HasColumnType("int");

                    b.Property<string>("UserNameInLocalLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Department_Id");

                    b.HasIndex("Rankid");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("Domain.Rank", b =>
                {
                    b.HasOne("Domain.RankType", "RankTypeIds")
                        .WithMany()
                        .HasForeignKey("RankTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RankTypeIds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.RoleClaims", b =>
                {
                    b.HasOne("Infrastructure.Data.Authentications.Roles", null)
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.AppUser", b =>
                {
                    b.HasOne("Domain.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("Rankid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departments");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Infrastructure.Data.Authentications.Roles", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
